// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeln_AOx2TXFiXQUEh8_zmPiOwQzbKPls',
    appId: '1:275330635554:web:89d9ac12edb7756308f77b',
    messagingSenderId: '275330635554',
    projectId: 'chatappflutter-main',
    authDomain: 'chatappflutter-main.firebaseapp.com',
    storageBucket: 'chatappflutter-main.appspot.com',
    measurementId: 'G-7DVQXWT8MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGxFenKj854nEebe3v_FGTWgKcRFolIw',
    appId: '1:275330635554:android:fe4bb6a0a1c7880c08f77b',
    messagingSenderId: '275330635554',
    projectId: 'chatappflutter-main',
    storageBucket: 'chatappflutter-main.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwVefsx8jhtSEor25nHFbobvgxFnB995s',
    appId: '1:275330635554:ios:4ebd553b08e5e3b108f77b',
    messagingSenderId: '275330635554',
    projectId: 'chatappflutter-main',
    storageBucket: 'chatappflutter-main.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwVefsx8jhtSEor25nHFbobvgxFnB995s',
    appId: '1:275330635554:ios:4ebd553b08e5e3b108f77b',
    messagingSenderId: '275330635554',
    projectId: 'chatappflutter-main',
    storageBucket: 'chatappflutter-main.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeln_AOx2TXFiXQUEh8_zmPiOwQzbKPls',
    appId: '1:275330635554:web:df8bc71aebf4f1d108f77b',
    messagingSenderId: '275330635554',
    projectId: 'chatappflutter-main',
    authDomain: 'chatappflutter-main.firebaseapp.com',
    storageBucket: 'chatappflutter-main.appspot.com',
    measurementId: 'G-F6KSYFLEFS',
  );

}